### ISSUE TITLE
Debug build_src.bash on Ubuntu 19

### ISSUE THREAD

**Issue by harry-ma-qiang** [harry-ma-qiang/ffmpeg-intel-qsv#1]
### Problems
build_src.bash is a script that can download the source code and configure and compile automatically. The goal of this script is to create executable FFmpeg on Linux. 

However, making hardware working properly on Linux is not always easy. This script used latest packages/source of Intel Media SDK.

It was tested on Ubuntu 19 only. Ubuntu 18 may also work, but CentOS 7.6 is unknown. The problem was gcc and linux kernel. 

But the compiled FFmpeg couldn't use qsv to do decoding or encoding or filtering. It seems the problem was VPP. Pls finish the following tasks for debugging and make this script works on Ubuntu 18/19, ie, generate a working ffmpeg for qsv accelerated transcoding. 

Pls read tutorials at bottom before working on this task.

### Tasks
- [x] Install Ubuntu server 18 / 19 without x11 dependencies: we may need to find what x11 dev are required, e.g. xserver-xorg-video-intel, during this tasks.
- [x] Install basic tools, like gcc, g++ make curl pkg-config yasm nasm cmake autoconf libtool
- [x] Compile depended libs for Intel Media Driver and SDK, build_src.bash is an example.
- [x] Find ways to verify the correctness of each libs. e.g. make check.
- [x] Finally, compile ffmpeg and do run transcoding test again.

Note there are two ways to use Intel Media SDK, `iHD` and `i965` (`i915` is out of dated), we need to discuss which one to use. 

### Reference
https://trac.ffmpeg.org/wiki/Hardware/QuickSync
https://gist.github.com/Brainiarc7/4f831867f8e55d35cbcb527e15f9f116
https://gist.github.com/andrearug/ee461152acfbbd3f52b3bb9ffb55b6b8
https://github.com/intel/media-driver
https://github.com/Intel-Media-SDK/MediaSDK
https://wiki.ubuntu.com/IntelQuickSyncVideo
https://github.com/Intel-Media-SDK/MediaSDK/wiki/Intel-media-stack-on-Ubuntu
http://www.linuxfromscratch.org/blfs/view/svn/x/x7driver.html

### Testing/Compiling Env
I will send you a machine in Shenzhen, you can send reboot or install OS request to our Shenzhen co-workers through WeChat. It is running a Ubuntu 18. I will send the login username/password to you via Whatsapp.

I also suggest you find a i5/7 PC by yourself with 8/16G memory for this task, compiling Intel Media SDK requires a large amount of memory. If you have difficulty with finding such a PC, let me know.

**Comment by harry-ma-qiang** [comment]
Finished, it works on Ubuntu 18 and Ubuntu 19.
